export const AUTH_FACEBOOK_REQUEST = 'auth/AUTH_FACEBOOK_REQUEST';
export const AUTH_FACEBOOK_SUCCESS = 'auth/AUTH_FACEBOOK_SUCCESS';
export const AUTH_FACEBOOK_ERROR = 'auth/AUTH_FACEBOOK_ERROR';
export const AUTH_FACEBOOK_LOGOUT = 'auth/AUTH_FACEBOOK_LOGOUT';
export const AUTH_FACEBOOK_CANCEL = 'auth/AUTH_FACEBOOK_CANCEL';
export const AUTH_FACEBOOK_REQUEST_MESSAGE = 'auth/AUTH_FACEBOOK_REQUEST_MESSAGE';
export const AUTH_FACEBOOK_RECEIVE_MESSAGE = 'auth/AUTH_FACEBOOK_RECEIVE_MESSAGE';
